#pragma once
#include "Window.h"

namespace Parrot
{
	enum class Window::Keyboard::Key : int32_t
	{
		PT_KEY_UNKNOWN = -1,
		PT_KEY_SPACE = 32,
		PT_KEY_APOSTROPHE = 39,
		PT_KEY_COMMA = 44,
		PT_KEY_MINUS = 45,
		PT_KEY_PERIOD = 46,
		PT_KEY_SLASH = 47,
		PT_KEY_0 = 48,
		PT_KEY_1 = 49,
		PT_KEY_2 = 50,
		PT_KEY_3 = 51,
		PT_KEY_4 = 52,
		PT_KEY_5 = 53,
		PT_KEY_6 = 54,
		PT_KEY_7 = 55,
		PT_KEY_8 = 56,
		PT_KEY_9 = 57,
		PT_KEY_SEMICOLON = 59,
		PT_KEY_EQUAL = 61,
		PT_KEY_A = 65,
		PT_KEY_B = 66,
		PT_KEY_C = 67,
		PT_KEY_D = 68,
		PT_KEY_E = 69,
		PT_KEY_F = 70,
		PT_KEY_G = 71,
		PT_KEY_H = 72,
		PT_KEY_I = 73,
		PT_KEY_J = 74,
		PT_KEY_K = 75,
		PT_KEY_L = 76,
		PT_KEY_M = 77,
		PT_KEY_N = 78,
		PT_KEY_O = 79,
		PT_KEY_P = 80,
		PT_KEY_Q = 81,
		PT_KEY_R = 82,
		PT_KEY_S = 83,
		PT_KEY_T = 84,
		PT_KEY_U = 85,
		PT_KEY_V = 86,
		PT_KEY_W = 87,
		PT_KEY_X = 88,
		PT_KEY_Y = 89,
		PT_KEY_Z = 90,
		PT_KEY_LEFT_BRACKET = 91,
		PT_KEY_BACKSLASH = 92,
		PT_KEY_RIGHT_BRACKET = 93,
		PT_KEY_GRAVE_ACCENT = 96,
		PT_KEY_WORLD_1 = 161,
		PT_KEY_WORLD_2 = 162,
		PT_KEY_ESCAPE = 256,
		PT_KEY_ENTER = 257,
		PT_KEY_TAB = 258,
		PT_KEY_BACKSPACE = 259,
		PT_KEY_INSERT = 260,
		PT_KEY_DELETE = 261,
		PT_KEY_RIGHT = 262,
		PT_KEY_LEFT = 263,
		PT_KEY_DOWN = 264,
		PT_KEY_UP = 265,
		PT_KEY_PAGE_UP = 266,
		PT_KEY_PAGE_DOWN = 267,
		PT_KEY_HOME = 268,
		PT_KEY_END = 269,
		PT_KEY_CAPS_LOCK = 280,
		PT_KEY_SCROLL_LOCK = 281,
		PT_KEY_NUM_LOCK = 282,
		PT_KEY_PRINT_SCREEN = 283,
		PT_KEY_PAUSE = 284,
		PT_KEY_F1 = 290,
		PT_KEY_F2 = 291,
		PT_KEY_F3 = 292,
		PT_KEY_F4 = 293,
		PT_KEY_F5 = 294,
		PT_KEY_F6 = 295,
		PT_KEY_F7 = 296,
		PT_KEY_F8 = 297,
		PT_KEY_F9 = 298,
		PT_KEY_F10 = 299,
		PT_KEY_F11 = 300,
		PT_KEY_F12 = 301,
		PT_KEY_F13 = 302,
		PT_KEY_F14 = 303,
		PT_KEY_F15 = 304,
		PT_KEY_F16 = 305,
		PT_KEY_F17 = 306,
		PT_KEY_F18 = 307,
		PT_KEY_F19 = 308,
		PT_KEY_F20 = 309,
		PT_KEY_F21 = 310,
		PT_KEY_F22 = 311,
		PT_KEY_F23 = 312,
		PT_KEY_F24 = 313,
		PT_KEY_F25 = 314,
		PT_KEY_KP_0 = 320,
		PT_KEY_KP_1 = 321,
		PT_KEY_KP_2 = 322,
		PT_KEY_KP_3 = 323,
		PT_KEY_KP_4 = 324,
		PT_KEY_KP_5 = 325,
		PT_KEY_KP_6 = 326,
		PT_KEY_KP_7 = 327,
		PT_KEY_KP_8 = 328,
		PT_KEY_KP_9 = 329,
		PT_KEY_KP_DECIMAL = 330,
		PT_KEY_KP_DIVIDE = 331,
		PT_KEY_KP_MULTIPLY = 332,
		PT_KEY_KP_SUBTRACT = 333,
		PT_KEY_KP_ADD = 334,
		PT_KEY_KP_ENTER = 335,
		PT_KEY_KP_EQUAL = 336,
		PT_KEY_LEFT_SHIFT = 340,
		PT_KEY_LEFT_CONTROL = 341,
		PT_KEY_LEFT_ALT = 342,
		PT_KEY_LEFT_SUPER = 343,
		PT_KEY_RIGHT_SHIFT = 344,
		PT_KEY_RIGHT_CONTROL = 345,
		PT_KEY_RIGHT_ALT = 346,
		PT_KEY_RIGHT_SUPER = 347,
		PT_KEY_MENU = 348
	};
}
	//static constexpr const char* key[] =
	//{
	//	"PT_KEY_UNKNOWN",
	//	"PT_KEY_SPACE",
	//	"PT_KEY_APOSTROPHE",
	//	"PT_KEY_COMMA",
	//	"PT_KEY_MINUS",
	//	"PT_KEY_PERIOD",
	//	"PT_KEY_SLASH",
	//	"PT_KEY_0",
	//	"PT_KEY_1",
	//	"PT_KEY_2",
	//	"PT_KEY_3",
	//	"PT_KEY_4",
	//	"PT_KEY_5",
	//	"PT_KEY_6",
	//	"PT_KEY_7",
	//	"PT_KEY_8",
	//	"PT_KEY_9",
	//	"PT_KEY_SEMICOLON",
	//	"PT_KEY_EQUAL",
	//	"PT_KEY_A",
	//	"PT_KEY_B",
	//	"PT_KEY_C",
	//	"PT_KEY_D",
	//	"PT_KEY_E",
	//	"PT_KEY_F",
	//	"PT_KEY_G",
	//	"PT_KEY_H",
	//	"PT_KEY_I",
	//	"PT_KEY_J",
	//	"PT_KEY_K",
	//	"PT_KEY_L",
	//	"PT_KEY_M",
	//	"PT_KEY_N",
	//	"PT_KEY_O",
	//	"PT_KEY_P",
	//	"PT_KEY_Q",
	//	"PT_KEY_R",
	//	"PT_KEY_S",
	//	"PT_KEY_T",
	//	"PT_KEY_U",
	//	"PT_KEY_V",
	//	"PT_KEY_W",
	//	"PT_KEY_X",
	//	"PT_KEY_Y",
	//	"PT_KEY_Z",
	//	"PT_KEY_LEFT_BRACKET",
	//	"PT_KEY_BACKSLASH",
	//	"PT_KEY_RIGHT_BRACKET",
	//	"PT_KEY_GRAVE_ACCENT",
	//	"PT_KEY_WORLD_1",
	//	"PT_KEY_WORLD_2",
	//	"PT_KEY_ESCAPE",
	//	"PT_KEY_ENTER",
	//	"PT_KEY_TAB",
	//	"PT_KEY_BACKSPACE",
	//	"PT_KEY_INSERT",
	//	"PT_KEY_DELETE",
	//	"PT_KEY_RIGHT",
	//	"PT_KEY_LEFT",
	//	"PT_KEY_DOWN",
	//	"PT_KEY_UP",
	//	"PT_KEY_PAGE_UP",
	//	"PT_KEY_PAGE_DOWN",
	//	"PT_KEY_HOME",
	//	"PT_KEY_END",
	//	"PT_KEY_CAPS_LOCK",
	//	"PT_KEY_SCROLL_LOCK",
	//	"PT_KEY_NUM_LOCK",
	//	"PT_KEY_PRINT_SCREEN",
	//	"PT_KEY_PAUSE",
	//	"PT_KEY_F1",
	//	"PT_KEY_F2",
	//	"PT_KEY_F3",
	//	"PT_KEY_F4",
	//	"PT_KEY_F5",
	//	"PT_KEY_F6",
	//	"PT_KEY_F7",
	//	"PT_KEY_F8",
	//	"PT_KEY_F9",
	//	"PT_KEY_F10",
	//	"PT_KEY_F11",
	//	"PT_KEY_F12",
	//	"PT_KEY_F13",
	//	"PT_KEY_F14",
	//	"PT_KEY_F15",
	//	"PT_KEY_F16",
	//	"PT_KEY_F17",
	//	"PT_KEY_F18",
	//	"PT_KEY_F19",
	//	"PT_KEY_F20",
	//	"PT_KEY_F21",
	//	"PT_KEY_F22",
	//	"PT_KEY_F23",
	//	"PT_KEY_F24",
	//	"PT_KEY_F25",
	//	"PT_KEY_KP_0",
	//	"PT_KEY_KP_1",
	//	"PT_KEY_KP_2",
	//	"PT_KEY_KP_3",
	//	"PT_KEY_KP_4",
	//	"PT_KEY_KP_5",
	//	"PT_KEY_KP_6",
	//	"PT_KEY_KP_7",
	//	"PT_KEY_KP_8",
	//	"PT_KEY_KP_9",
	//	"PT_KEY_KP_DECIMAL",
	//	"PT_KEY_KP_DIVIDE",
	//	"PT_KEY_KP_MULTIPLY",
	//	"PT_KEY_KP_SUBTRACT",
	//	"PT_KEY_KP_ADD",
	//	"PT_KEY_KP_ENTER",
	//	"PT_KEY_KP_EQUAL",
	//	"PT_KEY_LEFT_SHIFT",
	//	"PT_KEY_LEFT_CONTROL",
	//	"PT_KEY_LEFT_ALT",
	//	"PT_KEY_LEFT_SUPER",
	//	"PT_KEY_RIGHT_SHIFT",
	//	"PT_KEY_RIGHT_CONTROL",
	//	"PT_KEY_RIGHT_ALT",
	//	"PT_KEY_RIGHT_SUPER",
	//	"PT_KEY_MENU"
	//};
